### PR TITLE
Add a basic test to check GradCAM implemention

### PR DESCRIPTION
**Pull request by nalinimsingh**

### CODE REVIEW

**Comment by nsthorat** [comment]
This is great, thank you! Just curious, how are you running this test, directly by running `python grad_cam_test.py`?

**Comment by nalinimsingh** [comment]
I run `python -m saliency.grad_cam_test` from the PAIR-code/saliency directory. 

Do you have suggestions for a better way to set that up?

**Comment by nsthorat** [comment]
This seems fine, can you just add a comment to the top of the file explaining how to run it?

**Comment by nalinimsingh** [comment]
It's explained in the docstring at the top -- do you want it somewhere else?

**Comment by nalinimsingh** [comment]
Actually, I realized you're right that it's unintuitive to have that in the docstring for testGradCamGetMask. Moved it to a separate docstring for the whole test class.

**Comment by nsthorat** [comment]
Thanks!

**Pull request merged**
